### ISSUE TITLE
Ошибка в методе

### ISSUE THREAD

**Issue by diablont** [elemc/request#1]
// FinishError функция завершает запрос неудачно с кодом 500
func (r *Request) FinishError(msg string, args ...interface{}) {
	r.Log().
		WithField("status", http.StatusOK).
		Errorf("Response: %s", fmt.Sprintf(msg, args...))
	r.finish(http.StatusInternalServerError, msg, args...)
}

в лог пишется http.StatusOK

**Comment by elemc** [comment]
Исправил
